# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/opa_oz/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/opa_oz/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/opa_oz/CLionProjects/atomic_processors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/opa_oz/CLionProjects/atomic_processors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/opa_oz/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/opa_oz/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/opa_oz/CLionProjects/atomic_processors/CMakeFiles /Users/opa_oz/CLionProjects/atomic_processors//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/opa_oz/CLionProjects/atomic_processors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AtomicProcessors

# Build rule for target.
AtomicProcessors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AtomicProcessors
.PHONY : AtomicProcessors

# fast build rule for target.
AtomicProcessors/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AtomicProcessors.dir/build.make CMakeFiles/AtomicProcessors.dir/build
.PHONY : AtomicProcessors/fast

#=============================================================================
# Target rules for targets named FileType

# Build rule for target.
FileType: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileType
.PHONY : FileType

# fast build rule for target.
FileType/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/FileType.dir/build.make utils/CMakeFiles/FileType.dir/build
.PHONY : FileType/fast

#=============================================================================
# Target rules for targets named UtilsString

# Build rule for target.
UtilsString: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UtilsString
.PHONY : UtilsString

# fast build rule for target.
UtilsString/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/UtilsString.dir/build.make utils/CMakeFiles/UtilsString.dir/build
.PHONY : UtilsString/fast

#=============================================================================
# Target rules for targets named UtilsJSON

# Build rule for target.
UtilsJSON: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UtilsJSON
.PHONY : UtilsJSON

# fast build rule for target.
UtilsJSON/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/UtilsJSON.dir/build.make utils/CMakeFiles/UtilsJSON.dir/build
.PHONY : UtilsJSON/fast

#=============================================================================
# Target rules for targets named UtilsVector

# Build rule for target.
UtilsVector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UtilsVector
.PHONY : UtilsVector

# fast build rule for target.
UtilsVector/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/UtilsVector.dir/build.make utils/CMakeFiles/UtilsVector.dir/build
.PHONY : UtilsVector/fast

#=============================================================================
# Target rules for targets named UtilsWrite

# Build rule for target.
UtilsWrite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UtilsWrite
.PHONY : UtilsWrite

# fast build rule for target.
UtilsWrite/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/UtilsWrite.dir/build.make utils/CMakeFiles/UtilsWrite.dir/build
.PHONY : UtilsWrite/fast

#=============================================================================
# Target rules for targets named UtilsRead

# Build rule for target.
UtilsRead: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UtilsRead
.PHONY : UtilsRead

# fast build rule for target.
UtilsRead/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/UtilsRead.dir/build.make utils/CMakeFiles/UtilsRead.dir/build
.PHONY : UtilsRead/fast

#=============================================================================
# Target rules for targets named Pick

# Build rule for target.
Pick: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pick
.PHONY : Pick

# fast build rule for target.
Pick/fast:
	$(MAKE) $(MAKESILENT) -f subcommands/CMakeFiles/Pick.dir/build.make subcommands/CMakeFiles/Pick.dir/build
.PHONY : Pick/fast

#=============================================================================
# Target rules for targets named Unique

# Build rule for target.
Unique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Unique
.PHONY : Unique

# fast build rule for target.
Unique/fast:
	$(MAKE) $(MAKESILENT) -f subcommands/CMakeFiles/Unique.dir/build.make subcommands/CMakeFiles/Unique.dir/build
.PHONY : Unique/fast

#=============================================================================
# Target rules for targets named CSV2JSON

# Build rule for target.
CSV2JSON: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CSV2JSON
.PHONY : CSV2JSON

# fast build rule for target.
CSV2JSON/fast:
	$(MAKE) $(MAKESILENT) -f subcommands/CMakeFiles/CSV2JSON.dir/build.make subcommands/CMakeFiles/CSV2JSON.dir/build
.PHONY : CSV2JSON/fast

#=============================================================================
# Target rules for targets named Templater

# Build rule for target.
Templater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Templater
.PHONY : Templater

# fast build rule for target.
Templater/fast:
	$(MAKE) $(MAKESILENT) -f subcommands/CMakeFiles/Templater.dir/build.make subcommands/CMakeFiles/Templater.dir/build
.PHONY : Templater/fast

#=============================================================================
# Target rules for targets named ExtractLogs

# Build rule for target.
ExtractLogs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExtractLogs
.PHONY : ExtractLogs

# fast build rule for target.
ExtractLogs/fast:
	$(MAKE) $(MAKESILENT) -f projects/anime-alice/CMakeFiles/ExtractLogs.dir/build.make projects/anime-alice/CMakeFiles/ExtractLogs.dir/build
.PHONY : ExtractLogs/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AtomicProcessors.dir/build.make CMakeFiles/AtomicProcessors.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AtomicProcessors.dir/build.make CMakeFiles/AtomicProcessors.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AtomicProcessors.dir/build.make CMakeFiles/AtomicProcessors.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AtomicProcessors"
	@echo "... CSV2JSON"
	@echo "... ExtractLogs"
	@echo "... FileType"
	@echo "... Pick"
	@echo "... Templater"
	@echo "... Unique"
	@echo "... UtilsJSON"
	@echo "... UtilsRead"
	@echo "... UtilsString"
	@echo "... UtilsVector"
	@echo "... UtilsWrite"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

